namespace TSI_ERP_ETL.Models
{
    public record TierModel(DateTime? DateCin,
                            string? LieuCin,
                            string? NomPersonnePhysique,
                            string? ReferenceExonerationFodec,
                            DateTime? DateDebutExonerationFodec,
                            string? Email,
                            Guid? Devise,
                            string? LieuPasseport,
                            Guid TypeTier,
                            string? Pays,
                            bool? AppliquerTimbre,
                            string? Code,
                            string? NomAgence,
                            string? Ville,
                            Guid? Region,
                            string? NomBanque,
                            string? AutreInfo,
                            DateTime? DateFinExonerationTimbre,
                            DateTime? DateFinExonerationTva,
                            Guid? TypeOperationParDefaut,
                            decimal? CreditMax,
                            string? CodePatente,
                            Guid? Contacts,
                            string? RegistreCommerce,
                            string? NumeroCin,
                            DateTime? DateDebutExonerationTva,
                            string? TelephoneDomicilePraticien,
                            string? Rib,
                            string? ReferenceExonerationTimbre,
                            bool? AppliquerFodec,
                            string? NumPasseport,
                            string? Compte,
                            DateTime? DateDebutExonerationTimbre,
                            bool? TiersDouteux,
                            Guid Uid,
                            string? Observations,
                            string? SpecialitePraticien,
                            string? Telephone,
                            string? PrenomPersonnePhysique,
                            string? Nom,
                            string? ReferenceExonerationTva,
                            string? Telecopie,
                            string? PraticienClinique,
                            string? RaisonSociale,
                            string? Adresse,
                            double? TauxRemise,
                            bool? AccepterAssuranceVoiture,
                            DateTime? DateObtentionPermis,
                            string? AdresseDomicilePraticien,
                            Guid? ModaliteReglement,
                            string? NumeroPermis,
                            string? AdresseLocale,
                            DateTime? DateNaissance,
                            string? SiteWeb,
                            string? MatriculeFiscal,
                            string? LieuObtentionPermis,
                            DateTime? DatePasseport,
                            bool? AccepterAssuranceAccompagnant,
                            string? AdressePermanente,
                            string? AdresseLivraison,
                            DateTime? DateFinExonerationFodec,
                            string? CodePostal,
                            double? RetenueImpots,
                            int? Nombre,
                            string? Contact,
                            DateTime? EcheancePaiement,
                            string? Activite,
                            byte[]? Sigle,
                            int? Delai,
                            string? TypeIdentifiant,
                            double? TauxTva,
                            double? TauxFodec,
                            double? TauxDc,
                            Guid? Agence,
                            Guid? ModePaiement,
                            Guid? ModeReglement,
                            string? Tel,
                            double? Retenue,
                            string? Fax,
                            bool? Exonore,
                            string? CleMatriculeFiscal,
                            string? CategorieContribuable,
                            int? NumeroEtablissement,
                            string? CodeTva,
                            string? Notes,
                            bool? IsEtranger,
                            Guid? CompteComptable,
                            string? LibelleCompteComptable,
                            bool? ChequeGarantie,
                            bool? LimiteCredit,
                            bool? TiersAuComptant,
                            bool? PrendreConsChequePort,
                            bool? PrendreConsTraitPort,
                            decimal? MntCheGar,
                            decimal? MntLimiteCredit,
                            Guid? BanqueCheGar,
                            string? NumCheGar,
                            bool? ChequeBlanc,
                            Guid? Banque,
                            Guid? CategorieTiers,
                            bool? PrendreConsTraitEsc,
                            string? CodeImport,
                            bool? FinMois,
                            DateTime? DateChangementIdentifiant,
                            decimal? PourcAvanceSurImpot);
}

/*public IEnumerable<TierExonorationResponse> TierExonorations { get; set; } = Enumerable.Empty<TierExonorationResponse>();
public IEnumerable<ContactsResponse> ContactsNavigations { get; set; } = Enumerable.Empty<ContactsResponse>();
public IEnumerable<ContratMaintenanceResponse> ContratMaintenances { get; set; } = Enumerable.Empty<ContratMaintenanceResponse>();
public IEnumerable<TierExonorationFodecResponse> TierExonorationFodecs { get; set; } = Enumerable.Empty<TierExonorationFodecResponse>();
public IEnumerable<AdressesResponse> Adressess { get; set; } = Enumerable.Empty<AdressesResponse>();
public IEnumerable<InterventionResponse> Interventions { get; set; } = Enumerable.Empty<InterventionResponse>();
public IEnumerable<ProjetResponse> Projets { get; set; } = Enumerable.Empty<ProjetResponse>();
public IEnumerable<TimeSheetResponse> TimeSheets { get; set; } = Enumerable.Empty<TimeSheetResponse>();
public IEnumerable<DetailMatriculeFiscalResponse> DetailMatriculeFiscals { get; set; } = Enumerable.Empty<DetailMatriculeFiscalResponse>();*/